version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  assignees:
    - "sboulema"
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"