resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'sboulema/mtggoldfish'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: SSH@0
  displayName: 'Deploy an image'
  inputs:
    sshEndpoint: CurleezBox
    commands: /home/sboulema/deployDockerContainer MtgGoldfish mtggoldfish