# First Stage
# FROM monostream/nodejs-gulp-bower
FROM node:alpine
WORKDIR src

COPY . .

RUN npm install
RUN gulp build

# Second Stage
FROM nginx

COPY --from=0 /src/dist /usr/share/nginx/html/

EXPOSE 80